mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: silent
ipv6: true
external-controller: 127.0.0.1:9090

dns:
  enable: true                   
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - system # 使用 iOS 系统 DNS
  nameserver:
    - DOH1
    - DOH2

proxy-providers:

#全部節點
  All:
    type: http
#    url: "https://api.v1.mk/sub?target=clash&url=訂閱連結&list=true&udp=true"
    url: "訂閱連結"
    interval: 3600
    path: ./all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://captive.apple.com

proxies:
           

proxy-groups:
      
  - name: Others
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Rocket.png
    use:
      - All
    proxies:
      - DIRECT
      
  - name: Telegram
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png
    use:
      - All  
    proxies:
      - DIRECT 
      
  - name: Netflix
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png
    use:
      - All
    proxies:  
      - DIRECT
      
  - name: Disney+
    type: select
    icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/DisneyPlus.png
    use:
      - All
    proxies:
      - DIRECT
      
  - name: PTT
    type: select
    icon: https://iamchucky.github.io/PttChrome/icon_512.png
    use:
      - All
    proxies:   
      - DIRECT
      
  - name: China
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/383px-Flag_of_the_People%27s_Republic_of_China.svg.png
    use:
      - All
    proxies:
      - DIRECT
      
  - name: Porn
    type: select
#    type: url-test
#    url: 'http://captive.apple.com'
    interval: 300
    icon: https://www.vhv.rs/dpng/d/523-5234025_18-plus-png-emblem-transparent-png.png
    use:
      - All
    proxies:
      - DIRECT
      
  - name: Cloudflare
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Cloudflare_Logo.png/480px-Cloudflare_Logo.png
    use:
      - All
    proxies:
      - DIRECT



rule-providers:

  Netflix:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml"
    path: ./ruleset/Netflix.yaml
    interval: 86400

  Disney:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.yaml"
    path: ./ruleset/Disney.yaml
    interval: 86400
    
  Telegram:
    type: http
    behavior: ipcidr-text
    url: https://core.telegram.org/resources/cidr.txt
    path: ./ruleset/Telegram.txt
    interval: 86400   
    
  Porn-domain-text:
    type: http
    behavior: domain-text 
    url: https://leo15dev.github.io/Stash/rule/Porn.txt
    path: ./ruleset/Porn.txt
    interval: 86400

  PTT-domain-text:
    type: http
    behavior: domain-text 
    url: https://leo15dev.github.io/Stash/rule/PTT.txt
    path: ./ruleset/PTT.txt
    interval: 86400
    
#Clash
#  Porn:
#    type: http
#    behavior: classical
#    url: "https://leo15dev.github.io/Stash/rule/porn.yaml"
#    path: ./ruleset/Porn.yaml
#    interval: 86400

#  PTT:
#    type: http
#    behavior: classical
#    url: "https://leo15dev.github.io/Stash/rule/PTT.yaml"
#    path: ./ruleset/PTT.yaml
#    interval: 86400

  lan-cidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.txt
    interval: 86400
    
  Cloudflare-v4cidr:
    type: http
    behavior: ipcidr-text
    url: https://www.cloudflare.com/ips-v4
    path: ./ruleset/Cloudflare-v4cidr.txt
    interval: 86400

  Cloudflare-v6cidr:
    type: http
    behavior: ipcidr-text
    url: https://www.cloudflare.com/ips-v6
    path: ./ruleset/Cloudflare-v6cidr.txt
    interval: 86400


rules:
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Disney,Disney+
  - RULE-SET,Telegram,Telegram,no-resolve
  - RULE-SET,Porn-domain-text,Porn
  - RULE-SET,PTT-domain-text,PTT
  - RULE-SET,Cloudflare-v4cidr,Cloudflare
  - RULE-SET,Cloudflare-v6cidr,Cloudflare
  - RULE-SET,lan-cidr,DIRECT
  - GEOIP,TW,DIRECT
  - GEOIP,CN,China
  - MATCH,Others
