mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: silent
ipv6: true
external-controller: 127.0.0.1:9090

dns:
  enable: true                   
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - system # 使用 iOS 系统 DNS
  nameserver:
    - DOH1
    - DOH2

proxy-providers:

#全部節點
  All:
    type: http
#    url: "https://api.v1.mk/sub?target=clash&url=訂閱連結&list=true&udp=true"
    url: "訂閱連結"
    interval: 3600
    path: ./all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://captive.apple.com

proxies:
           

proxy-groups:
  - name: 手動切換
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Rocket.png
    use:
      - All        
      
  - name: Telegram
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png
    use:
      - All  
    proxies:
      - DIRECT 
      
  - name: Netflix
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png
    use:
      - All
    proxies:  
      - DIRECT
      
  - name: Disney+
    type: select
    icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/DisneyPlus.png
    use:
      - All
    proxies:
      - DIRECT
      
  - name: PTT
    type: select
    icon: https://iamchucky.github.io/PttChrome/icon_512.png
    use:
      - All
    proxies:
      - DIRECT

  - name: 國外網站
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png
    use:
      - All
    proxies:
      - DIRECT
      
  - name: Porn
    type: select
#    type: url-test
#    url: 'http://captive.apple.com'
    interval: 300
    icon: https://www.vhv.rs/dpng/d/523-5234025_18-plus-png-emblem-transparent-png.png
    use:
      - All
    proxies:
      - DIRECT


rule-providers:

  Netflix:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml"
    path: ./ruleset/Netflix.yaml
    interval: 86400

  Disney:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.yaml"
    path: ./ruleset/Disney.yaml
    interval: 86400
    
  Telegram:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Hackl0us/SS-Rule-Snippet@master/Rulesets/Clash/App/social/Telegram.yaml"
    path: ./ruleset/Telegram.yaml
    interval: 86400
    
  Porn-domain-text:
    behavior: domain-text 
    url: https://leo15dev.github.io/Stash/rule/Porn.txt
    path: ./ruleset/Porn.txt
    interval: 86400

  PTT-domain-text:
    behavior: domain-text 
    url: https://leo15dev.github.io/Stash/rule/PTT.txt
    path: ./ruleset/PTT.txt
    interval: 86400
    
#Clash
#  Porn:
#    type: http
#    behavior: classical
#    url: "https://leo15dev.github.io/Stash/rule/porn.yaml"
#    path: ./ruleset/Porn.yaml
#    interval: 86400

#  PTT:
#    type: http
#    behavior: classical
#    url: "https://leo15dev.github.io/Stash/rule/PTT.yaml"
#    path: ./ruleset/PTT.yaml
#    interval: 86400

rules:
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Disney,Disney+
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Porn,Porn
  - RULE-SET,PTT,PTT
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR,224.0.0.0/4,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  - GEOIP,TW,DIRECT
  - GEOIP,CN,國外網站
